cfg_name: 'default'

# dataset
raw_base_dir: '/home/ljf/Dataset/Sintel/scene'
prepared_base_dir: '/home/ljf/Dataset/sintel_release'
gt_2012_dir: '/media/ljf/Work/DATASET/kitti-flow/kitti2012/training'
gt_2015_dir: '/media/ljf/Work/DATASET/kitti-flow/kitti2015/data_scene_flow/training'
static_frames_txt: '/home/ljf/TrianFlow/data/eigen/static_frames.txt'
test_scenes_txt: '/home/ljf/TrianFlow/data/eigen/test_scenes.txt'
dataset: 'sintel_raw'
num_scales: 3
stride: 2

# training
num_iterations: 200000

# loss hyperparameters
w_ssim: 0.85 # w_pixel = 1 - w_ssim
w_flow_smooth: 10.0
w_flow_consis: 0.01

h_flow_consist_alpha: 3.0
h_flow_consist_beta: 0.05


# basic info
img_hw: [448, 1024]
# img_hw: [384, 832]
use_svd_gpu: False

